// GENERATED by tools/r6_takken_028_release.py. Do not hand-edit.
// A blocked spec contains no problem text, choices, or answer payload.
var TAKKEN_R6_028_RELEASE_SPEC_ = {
  "approvalEvidenceSha256": "7f175918237e029ea86f71c78620de668ac3bbb0cc704fc384be05cddc222922",
  "beforeValues": {
    "stem": "宅地建物取引業者A（消費税課税事業者）及び宅地建物取引業者B（消費税免税事業者）が受領した報酬に関するアからウの記述のうち、宅地建物取引業法の規定に違反しないものの組合せは1から4のうちどれか。なお、代理、媒介に当たり、広告の依頼は行われていないものとする。また、貸借の代理又は媒介をする宅地又は建物は長期の空家等には該当しない。"
  },
  "beforeValuesSha256": "e5a186b22d043436f1a9c41fe72ab822b4eef27950f64dca734317d0f0e6055d",
  "expectedAfterRuntimeRowSha256": "76907447f2ab2284abce7a095a124493c6b4931d4782aa454680cfe74d2ab636",
  "expectedBeforeRuntimeRowSha256": "07af011a08d499a4f247e93ca92ab7f85334bf096e5af09f2f57ad57b413301e",
  "expectedLabelSequence": "ア・イ・ウ",
  "fieldWhitelist": [
    "stem"
  ],
  "liveBaselineOverrides": {
    "explainLong": ""
  },
  "liveDateOnlyFields": [
    "updatedAt"
  ],
  "liveDiagnosticReceiptSha256": "b73cffb1a1e5cf43fc5894edb5107c20d5fbc9bd06a39bd280425d344c810925",
  "officialSourcePage": 16,
  "officialSourceSha256": "82a95815f991567ebc4982b05a15a71f6ec942bd6794c3bafe3bcf9c2e985bae",
  "qId": "R6takken-028",
  "releaseStatus": "approved",
  "replacementValues": {
    "stem": "宅地建物取引業者Ａ（消費税課税事業者）及び宅地建物取引業者Ｂ（消費税免税事業者）が受領した報酬に関するアからウの記述のうち、宅地建物取引業法の規定に違反しないものの組合せは1から4のうちどれか。なお、代理、媒介に当たり、広告の依頼は行われていないものとする。\nア　居住用建物（1か月の借賃12万円。消費税等相当額を含まない。）について、Ａは貸主から代理を依頼され、Ｂは借主から媒介を依頼され、Ａは貸主から6.7万円、Ｂは借主から6.5万円を報酬として受領した。なお、Ｂは、媒介の依頼を受けるに当たって、報酬について借主から特段の承諾を得ていない。\nイ　Ｂは、事業用建物について、貸主と借主双方から媒介を依頼され、借賃1か月分10万円（消費税等相当額を含まない。）、権利金90万円（権利設定の対価として支払われる金銭であって返還されないもので、消費税等相当額を含まない。）の賃貸借契約を成立させ、貸主と借主からそれぞれ5万円を報酬として受領した。\nウ　Ａは、土地付建物について、売主と買主双方から媒介を依頼され、代金3,500万円（消費税等相当額を含み、土地代金は2,400万円である。）の売買契約を成立させ、売主と買主からそれぞれ110万円を報酬として受領したほか、売主の特別の依頼に基づき行った遠隔地への現地調査に要した実費の費用について、売主が事前に負担を承諾していたので、売主から9万円を受領した。"
  },
  "replacementValuesSha256": "78f45dc80826c7c804f7df691903bcc3585dd269f09b97cefe987127833ccc66",
  "reviewedAt": "2026-08-22",
  "sourceAfterRuntimeRowSha256": "d60ef8583bbd59b9212e128c601367734d939804f3ae21bb5f3050453168eed9",
  "sourceBeforeRuntimeRowSha256": "5531d591e1f07b2bc5b60c1e5f31b46e9723fd781ac2a31d11d12249d82f3919",
  "sourceKind": "RETIO_official_question_pdf"
};
